### PR TITLE
Adding link to GH discussions to contributing.md

### PR DESCRIPTION
**Pull request by jukent**

### CODE REVIEW

**Comment by brian-rose** [comment]
I think this looks great, and we should close #24 and merge this one instead.

**Review by kmpaul — COMMENTED** [review]
This includes changes from #24, too.  We should merge this after #24...and there will probably be conflicts.

**Comment by jukent** [comment]
> This includes changes from #24, too. We should merge this after #24...and there will probably be conflicts.

Sorry about including those changes -- I pulled them in so that I could build the site. I think since GitHub knows they are from the same source we won't have conflicts (?). If we do I can fix them stat.

**Review by clyne — APPROVED** [review]

**Comment by kmpaul** [comment]
No conflicts with #24.  We can move forward with this PR whenever it is approved.

**Review by kmpaul — APPROVED** [review]
I think this looks good.

**Comment by jukent** [comment]
> No conflicts with #24. We can move forward with this PR whenever it is approved.

Merging now

**Pull request merged**
