### PR TITLE
Use foundations/cookbook infrastructure

### PR DESCRIPTION
**Pull request by jukent**
Makes GH actions match the cookbooks and the foundations page.

See https://github.com/ProjectPythia/pythia-foundations/pull/339

and conversation on https://github.com/ProjectPythia/projectpythia.github.io/pull/307

### CODE REVIEW

**Comment by jukent** [comment]
`  Examining conflict for urllib3: : 54it [02:10,  1.42s/it]::warning::%0D                                                         %0D
  
                                                           
  failed
  Warning: 
  UnsatisfiableError: The following specifications were found to be incompatible with a past
  explicit spec that is not an explicit spec in this operation (pip):
  
    - mamba -> conda[version='4.6.*,<4.13.0|4.6.*|4.7.*,<4.13.0|>=22.11.0,<23.4|>=4.8,<23.4|>=4.8,<5|>=4.8|>=4.8,<4.13.0|>=4.7.12,<4.13.0|>=4.7.12,<4.8']
    - mamba -> conda[version='>=22.11.0,<23.4'] -> conda-package-handling[version='>=1.3.0']
    - mamba -> conda[version='>=22.11.0,<23.4'] -> pluggy[version='>=1.0.0']
    - mamba -> conda[version='>=22.11.0,<23.4'] -> pycosat[version='>=0.6.3']
    - mamba -> conda[version='>=22.11.0,<23.4'] -> pyopenssl[version='>=16.2.0']
    - mamba -> conda[version='>=22.11.0,<23.4'] -> requests[version='>=2.18.4,<3|>=2.20.1,<3']
    - mamba -> conda[version='>=22.11.0,<23.4'] -> ruamel.yaml[version='>=0.11.14,<0.18']
    - mamba -> conda[version='>=22.11.0,<23.4'] -> setuptools[version='>=31.0.1']
    - mamba -> conda[version='>=22.11.0,<23.4'] -> toolz[version='>=0.8.1']
    - mamba -> conda[version='>=22.11.0,<23.4'] -> tqdm[version='>=4']
    - mamba -> libgcc-ng[version='>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0']
    - mamba -> libgcc-ng[version='>=9.4.0'] -> _libgcc_mutex[version='*|0.1',build='conda_forge|main|main']
    - mamba -> libgcc-ng[version='>=9.4.0'] -> _openmp_mutex[version='>=4.5']
    - mamba -> libmambapy==1.2.0=py38h7fa060d_0 -> libgcc-ng[version='>=10.3.0|>=12|>=11.2.0|>=4.9|>=7.2.0|>=12.1.0']
    - mamba -> libmambapy==1.2.0=py38h7fa060d_0 -> libstdcxx-ng[version='>=10.3.0|>=11.2.0|>=12|>=4.9|>=7.2.0|>=12.1.0']
    - mamba -> libstdcxx-ng[version='>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0']
    - mamba -> openssl[version='>=1.1.1f,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.1.1h,<1.1.2a|>=1.1.1i,<1.1.2a|>=1.1.1j,<1.1.2a|>=1.1.1k,<1.1.2a|>=1.1.1l,<1.1.2a|>=1.1.1n,<1.1.2a|>=1.1.1o,<1.1.2a|>=1.1.1q,<1.1.2a|>=1.1.1s,<1.1.2a|>=3.0.7,<4.0a0']
    - mamba -> openssl[version='>=3.0.7,<4.0a0'] -> ca-certificates
    - mamba -> python[version='>=3.8,<3.9.0a0'] -> bzip2[version='>=1.0.6,<2.0a0|>=1.0.8,<2.0a0']
    - mamba -> python[version='>=3.8,<3.9.0a0'] -> ld_impl_linux-64[version='>=2.34|>=2.36.1']
    - mamba -> python[version='>=3.8,<3.9.0a0'] -> libffi[version='3.2.*|>=3.2.1,<3.3.0a0|>=3.3,<3.4.0a0|>=3.4,<4.0a0|>=3.4.2,<3.5.0a0|>=3.4,<3.5|>=3.2.1,<3.3a0']
    - mamba -> python[version='>=3.8,<3.9.0a0'] -> libuuid[version='>=1.0.3,<2.0a0|>=1.41.5,<2.0a0|>=2.32.1,<3.0a0']
    - mamba -> python[version='>=3.8,<3.9.0a0'] -> ncurses[version='5.9.*|5.9|>=6.1,<7.0.0a0|>=6.2,<7.0.0a0|>=6.3,<7.0a0|>=6.2,<7.0a0|>=6.1,<7.0a0|>=6.2,<6.3.0a0|>=6.0,<7.0a0|6.0.*']
    - mamba -> python[version='>=3.8,<3.9.0a0'] -> openssl[version='1.0.*|>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1e,<1.1.2a|>=3.0.0,<4.0a0|>=3.0.2,<4.0a0|>=3.0.3,<4.0a0|>=3.0.5,<4.0a0|>=1.1.1m,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.0.2n,<1.0.3a|>=1.0.2m,<1.0.3a|>=1.0.2l,<1.0.3a']
    - mamba -> python[version='>=3.8,<3.9.0a0'] -> pip
    - mamba -> python[version='>=3.8,<3.9.0a0'] -> readline[version='6.2.*|7.0|>=7.0,<8.0a0|>=8.0,<9.0a0|>=8.1,<9.0a0|>=8.1.2,<9.0a0|>=8.2,<9.0a0|7.*|7.0.*']
    - mamba -> python[version='>=3.8,<3.9.0a0'] -> sqlite[version='3.13.*|3.20.*|>=3.24.0,<4.0a0|>=3.25.1,<4.0a0|>=3.25.2,<4.0a0|>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.28.0,<4.0a0|>=3.30.0,<4.0a0|>=3.30.1,<4.0a0|>=3.32.3,<4.0a0|>=3.33.0,<4.0a0|>=3.34.0,<4.0a0|>=3.35.5,<4.0a0|>=3.36.0,<4.0a0|>=3.37.0,<4.0a0|>=3.37.1,<4.0a0|>=3.40.1,<4.0a0|>=3.40.0,<4.0a0|>=3.39.3,<4.0a0|>=3.38.0,<4.0a0|>=3.35.4,<4.0a0|>=3.31.1,<4.0a0|>=3.38.5,<4.0a0|>=3.39.2,<4.0a0|>=3.38.3,<4.0a0|>=3.38.2,<4.0a0|>=3.39.1,<4.0a0|>=3.37.2,<4.0a0|>=3.29.0,<4.0a0|>=3.27.2,<4.0a0|>=3.23.1,<4.0a0|>=3.22.0,<4.0a0|>=3.20.1,<4.0a0']
    - mamba -> python[version='>=3.8,<3.9.0a0'] -> tk[version='8.5.*|8.6.*|>=8.6.10,<8.7.0a0|>=8.6.11,<8.7.0a0|>=8.6.12,<8.7.0a0|>=8.6.9,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.7,<8.7.0a0']
    - mamba -> python[version='>=3.8,<3.9.0a0'] -> xz[version='5.2.*|>=5.2.10,<6.0a0|>=5.2.4,<5.3.0a0|>=5.2.5,<5.3.0a0|>=5.2.6,<6.0a0|>=5.2.5,<6.0a0|>=5.2.4,<6.0a0|>=5.2.8,<6.0a0|>=5.2.6,<5.3.0a0|>=5.2.3,<5.3.0a0|>=5.2.3,<6.0a0']
    - mamba -> python[version='>=3.8,<3.9.0a0'] -> zlib[version='1.2.*|1.2.11|>=1.2.11,<1.3.0a0|>=1.2.13,<1.3.0a0|>=1.2.12,<1.3.0a0|1.2.8|1.2.11.*']
    - mamba -> python[version='>=3.9,<3.10.0a0'] -> tzdata`

**Comment by jukent** [comment]
I'm not sure why the environment is failing. It examines conflicts for a good 6 minutes. I'm not seeing anything obviously different between this environment.yml file and the ones in the other repositories. Can anybody else take a look?

**Comment by jukent** [comment]
I think the link checker might be built wrong too, but it should at least pass the environment build step.

**Comment by brian-rose** [comment]
@jukent I suggest holding off on this until https://github.com/ProjectPythia/pythia-foundations/pull/339 is resolved and merged. At that point, I think it will be easier to get this align this repo's actions with the cookbooks and foundations which will all be working the same way.

**Pull request closed without merging**
