### PR TITLE
Make environment.yml consistent with requirements.txt

### LINKED ISSUE #68: Sphinx error building the portal site locally
**What happened**:

I tried to build the portal site locally on my Mac laptop while developing #67. I followed the procedure for this described on our [Contributor's Guide](https://projectpythia.org/pages/contributing.html#to-build-and-view-the-site-locally) to set up and activate a dedicated conda environment and then build the site using sphinx.

I got the following error:
```
Theme error:
An error happened in rendering the page index.
Reason: TypeError("generate_nav_html() missing 1 required positional argument: 'kind'")
make: *** [html] Error 2
```

**What you expected to happen**:

The site should build normally without error.

**Minimal Complete Verifiable Example**:

From repository root directory:
```bash
cd content
conda env create -f ../ci/environment.yml
conda activate pythia
make html
```

**Anything else we need to know?**:

**Environment**:

- Python version: 3.9.2
- Sphinx version: 3.5.4
- conda version: 4.9.2
- Operating System: macOS Catalina 10.15.7
- Install method (conda, pip, source): conda, as described above

### PR DESCRIPTION
**Pull request by brian-rose**
Fixes #68 

This just makes our `ci/environment.yml` file (used by conda to make the build environment when building the site locally) consistent with `requirements.txt` (used by pip to make the build environment on readthedocs)

It would be better to avoid duplicating the build requirements. I'll open a separate issue about that.

### CODE REVIEW

**Comment by brian-rose** [comment]
@ktyle if you get a chance, can you check that this PR fixes #68 on linux as well?

**Review by ktyle — COMMENTED** [review]
In my case, I did not add pyyaml ... suspect it got installed as a prereq when building the conda environment. Is pyyaml included in the requirements.txt, so you included it here for consistency?

**Comment by brian-rose** [comment]
> In my case, I did not add pyyaml ... suspect it got installed as a prereq when building the conda environment. Is pyyaml included in the requirements.txt, so you included it here for consistency?

Yes, exactly. I just made this list mirror exactly what's in `requirements.txt`. I'm not 100% sure what pyyaml actually is...

**Comment by ktyle** [comment]
@brian-rose yes, #68 builds fine now on Linux.

**Review by ktyle — APPROVED** [review]

**Review by andersy005 — APPROVED** [review]

**Pull request merged**
