### PR TITLE
add AMS 2021 talk to about.md

### LINKED ISSUE #27: Add AMS recorded presentation
The recorded AMS presentation gives an overview of Project Pythia and should probably be accessible from the web site (not as educational content, but something for the "about project pythia"). This begs the question of where videos should live. Should we simply upload to youtube? Would it make sense to have a "Project Pythia" channel on YouTube? Is this more fodder for our contributors guide. The link to the AMS talk is here:

https://drive.google.com/file/d/1JfBDF978grhcdIKcRgpPUYD84tX2R9OL/view?usp=sharing

### PR DESCRIPTION
**Pull request by jukent**
I added the AMS talk from @clyne to the about page. I embedded it near the top because I thought that looked better, but am open to other opinions.

Closes #27

### CODE REVIEW

**Review by clyne — COMMENTED** [review]
Thanks @jukent. I don't have a strong opinion, but I guess i'd be inclined to put the video at the bottom with my thinking being that most people will just want to read about project for expediency, rather than wade through a 15 minute video. 

I think we also need to resolve the issue of where to host video: on google drive (as in this PR), youtube, or perhaps somewhere else? I like youtube because their recommender may help drive others to our content AND because it automatically gathers view metrics. MetPy uses youtube for their training videos. CCing @dopplershift for his input

**Comment by jukent** [comment]
@clyne If we put the video at the bottom I think we need to add a title before it to distinguish it from the "Training Material" section. Perhaps:

```
## AMS 2021 Project Pytia Presentation

Watch this recorded video from AMS 2021 to learn more about Project Pythia!
[video]
```

**Comment by jukent** [comment]
> I think we also need to resolve the issue of where to host video: on google drive (as in this PR), youtube, or perhaps somewhere else? I like youtube because their recommender may help drive others to our content AND because it automatically gathers view metrics. MetPy uses youtube for their training videos. CCing @dopplershift for his input

That makes sense to me! I suppose the first step is making a ProjectPythia Youtube account. I believe we can create one with multiple email address allowed to make edits.

**Review by kmpaul — COMMENTED** [review]
Should this be in the `pages/about.md` file or in the `index.md` file (i.e., landing page)?

**Comment by dopplershift** [comment]
IMO, Google Drive is not a video hosting solution--it's for storing documents (which happens to include video) and sharing them with some people. YouTube feels like the right solution, especially because you'll have much better UX as well as better searching and discoverability. Also, you can collect view metrics on YouTube which may be useful.

**Comment by jukent** [comment]
> IMO, Google Drive is not a video hosting solution--it's for storing documents (which happens to include video) and sharing them with some people. YouTube feels like the right solution, especially because you'll have much better UX as well as better searching and discoverability. Also, you can collect view metrics on YouTube which may be useful.

Makes sense. Should one of the PI's make the official Youtube channel?

**Comment by jukent** [comment]
> Should this be in the `pages/about.md` file or in the `index.md` file (i.e., landing page)?

I thought `about.md` but we can poll more opinions -- especially if we want to change the video location before a merge.

**Review by kmpaul — DISMISSED** [review]
Looks good!  Thanks @jukent!

**Review by ktyle — CHANGES_REQUESTED** [review]
Looks good except "Pytia" needs to be corrected to "Pythia" .

**Comment by jukent** [comment]
> Looks good except "Pytia" needs to be corrected to "Pythia" .

Thanks for catching that!

**Review by kmpaul — APPROVED** [review]

**Comment by jukent** [comment]
Can anyone help me figure out why the build is failing? The error message is `ValueError(f"token map not set: {token}")`

**Review by clyne — APPROVED** [review]
Looks great. Thanks!

**Comment by kmpaul** [comment]
> Can anyone help me figure out why the build is failing? The error message is `ValueError(f"token map not set: {token}")`

@jukent:  Yes.  I'm seeing this, too.  It appears to be cause by version 0.13.2 of `myst-parser`.  PIP installs version 0.13.2 of `myst-parser` while Conda installs 0.12.10.  I think that we can pin the versions of `myst-nb` to 0.10.1 and it should fix itself.

**Review by kmpaul — APPROVED** [review]

**Comment by kmpaul** [comment]
This is fixed, now.  The ReadTheDocs autobuild feature and the GitHub actions are now working, again.

**Comment by jukent** [comment]
@ktyle Can you re-review and confirm that your requested changes have been resolved? 
Then I believe this is ready to merge.

**Review by ktyle — APPROVED** [review]
LGTM!

**Pull request merged**
