### PR TITLE
Use the new publish_dir option for deploy-book workflow

### LINKED ISSUE #329: Site is not publishing to GitHub Pages
As discussed in https://github.com/ProjectPythia/projectpythia.github.io/pull/328, there is something wrong with the actions that take the rendered site and publish it on GitHub Pages so it's visible at https://projectpythia.org.

The published site is served from the [gh-pages branch of the repo](https://github.com/ProjectPythia/projectpythia.github.io/tree/gh-pages), which hasn't seen any new pushes in the last three months.

### PR DESCRIPTION
**Pull request by brian-rose**
Resolves #329

### CODE REVIEW

**Comment by brian-rose** [comment]
This needs to be merged before we can actually test if it's working since the preview deployment workflow is running from main branch.

**Comment by ktyle** [comment]
@brian-rose Great! I notice that the modification that @jukent made in #328 isn't showing up on the preview yet, though.

**Comment by brian-rose** [comment]
> @brian-rose Great! I notice that the modification that @jukent made in #328 isn't showing up on the preview yet, though.

Yeah, due to quirks in how GitHub actions work, we need to merge this first before we can test it.

**Review by ktyle — APPROVED** [review]
Great job! Given the importance of this change, I think we should merge ASAP.

**Comment by brian-rose** [comment]
> Great job! Given the importance of this change, I think we should merge ASAP.

Thanks, I'll merge and test right now.

**Pull request merged**
