### PR TITLE
add YouTube navbar link

### PR DESCRIPTION
**Pull request by jukent**
Adding link to YouTube channel to Portal navbar.

### CODE REVIEW

**Comment by brian-rose** [comment]
Seems like something went wrong with the preview for this PR. @jukent maybe try pushing another small change to this branch?

**Comment by jukent** [comment]
> Seems like something went wrong with the preview for this PR. @jukent maybe try pushing another small change to this branch?

Thanks for pointing this out, it was building before. I just merged from upstream, hopefully that helps.

**Comment by jukent** [comment]
It seems to be deployed now at https://623dfe214738c000717b7855--projectpythia-org.netlify.app/ @brian-rose

**Review by brian-rose — APPROVED** [review]
Looks great, works as advertised!

**Review by kmpaul — APPROVED** [review]
LGTM!  Thanks, @jukent!

**Pull request merged**
