### PR TITLE
Use Font Awesome Icons for "Start Learning" Sections

### PR DESCRIPTION
**Pull request by jukent**
Under "Start Learning" we have: the Foundations Book, the Resource Gallery, the Webinar Tutorial Series, the Pythia Data Collection, and Pythia Cookbooks. I'd like to use Font Awesome icons and a grid view to make this more visually appealing than scrolling through text blocks.

### CODE REVIEW

**Comment by jukent** [comment]
I think I need to set up a FA kit.

**Comment by kmpaul** [comment]
The fa-kit should not be necessary.  It should be built in to the PyData Sphinx Theme, which our theme depends on.  So, it should already be there.

**Comment by jukent** [comment]
@kmpaul Should I only have to make edits to `portal/index.md` to add the icons?
And I'll have to make changes to the sphinx-pythia-theme repo to change the layout?

**Comment by kmpaul** [comment]
You shouldn't have to change anything in the theme.  You should only have to use the icons in the main page (`portal/index.md`).

**Comment by kmpaul** [comment]
You probably want to use something like [Sphinx Panels](https://sphinx-panels.readthedocs.io/en/latest/).

**Comment by jukent** [comment]
I think these look worse than what we have now, so I'm going to close this PR.

**Pull request closed without merging**
