### PR TITLE
add blog infrastructure

### PR DESCRIPTION
**Pull request by jukent**
Adding blog infrastructure using [Ablog](https://ablog.readthedocs.io/en/stable/) as a place to make updates and announcements.

We might also want to embed the most recent update somewhere on the index homepage, but that is an extra layer of complexity.

Adding a navbar link to the Blog makes other Pythia pages more findable ([About Project Pythia](https://github.com/ProjectPythia/projectpythia.github.io/compare/about.html), [Contributor’s Guide](https://github.com/ProjectPythia/projectpythia.github.io/compare/contributing.html), and [Code of Conduct](https://github.com/ProjectPythia/projectpythia.github.io/compare/code_of_conduct.html)), but also duplicates a link to the resource gallery. This highlights some other weeds in our portal code.  

I think we should have a larger discussion about what we want this left navbar to look like, but that shouldn't block the inclusion of a blog.

Also, will have to add the blog to Foundations and Cookbook-Gallery navbars separately.

### CODE REVIEW

**Comment by jukent** [comment]
Screen Shot 2023-08-08 at 1 02 59 PM

**Comment by jukent** [comment]
The left nav bar in question is determined by the toc at the end of the index.md page
```
---
hidden: True
maxdepth: 1
---
about.md
contributing.md
code_of_conduct.md
cookbook-gallery.md
resource-gallery.md
```
I think we should remove the resource-gallery from here, and maybe add a separate how-to-cite page (even though this is proposed in a PR to be on the main page, thoughts?).

**Comment by brian-rose** [comment]
Hi @jukent, a lot of ideas / questions here!

I think adding a blog is a great idea. I also use the ablog package for my personal site.

I think there are a lot of design decisions about our home page / site navigation that are out of date and should be reconsidered. My suggestion for now is to avoid trying to solve too many problems at once. Let's get the blog going (yay!) and then devote some upcoming meeting time to brainstorming an overhaul of the site navigation.

It would be great to have a prominent "latest posts" section easily visible from the home page for news and announcements, but let's deal with that separately.

**Review by brian-rose — APPROVED** [review]
The first blog post looks great! We'll figure out the bigger picture of site navigation later.

**Comment by jukent** [comment]
Yay thanks @brian-rose I tried not to push any changes related to other site navigation issues, but adding the blog highlighted them in my mind. Happy to discuss this more on Monday.

**Comment by clyne** [comment]
@jukent is there any documentation (contributor's guide) on how to create a new blog post with ablog?

**Comment by jukent** [comment]
There should be! I'll add that. For now I believe, if you just make a .md file in the `posts/` folder that has this header 
```
---
blogpost: true
date: Aug 29, 2023
author: John Clyne
tags: cook-off
---
```
it will appear in the blog

**Comment by clyne** [comment]
Cool. Thanks!

**Comment by clyne** [comment]
Uh oh. That doesn't seem to be working for me. The new blog post does not appear when I test locally. I've done a complete environment install from scratch and have followed our contributor's [guide](https://github.com/ProjectPythia/projectpythia.github.io/blob/main/CONTRIBUTING.md). The new file, `cookoff2024-savethedate.md` simply contains:

```
---
blogpost: true
date: August 29, 2023
author: John Clyne
tags: cook-off
---

# Pythia Cookbook Cook-Off Hackathon 2024 - Save the Date!

The 2024 Pythia Cookbook Cook-Off Hackathon will take place June
10 - 14, at the NCAR Mesa Lab, located in Boulder, Colorado. Save
the date. More details to come!
```

**Comment by brian-rose** [comment]
@clyne try explicitly setting
```
date: Aug 29, 2023
```
and see if that helps.

I can't find it mentioned anywhere in the [ablog docs](https://ablog.readthedocs.io/en/stable/) but all the examples seem to use three letter months.

**Comment by clyne** [comment]
Thanks, @brian-rose, but no dice. The `blog` menu item links to https://projectpythia.org/blog. I'm guessing this is resolving to the production site, and there is no way to preview the results (until the PR is merged)???

**Comment by jukent** [comment]
@clyne one hiccup of our navbars is that if you click the "blog" option is directs you to the real published site and out of the preview. Are you clicking that button? If so, try adding `/blog` to the URL path manually instead.

**Comment by clyne** [comment]
Yes, that works. Thank you. Should we be using relative URLs where possible to avoid this problem, or would that open up another can of worms?

**Comment by jukent** [comment]
Yes I'll investigate that this week. I think it's kept this way to keep the navbar consistent across repositories. But I think it can be a relative link from the portal, if not from foundations.

**Comment by clyne** [comment]
Thanks, @jukent. Probably not a high priority - I don't think we get a lot of external contributions to the portal:-)

**Comment by brian-rose** [comment]
Yes we are duplicating / triplicating a bunch of code to create the same navbar from different repositories, with this unfortunately side-effect in the previews. There must be a better way to do it. Maybe that will follow from our Sphinx theme reboot efforts.

**Pull request merged**
