### PR TITLE
Add first draft of CODEOWNERS file

### PR DESCRIPTION
**Pull request by kmpaul**
The GitHub usernames listed in this file will be triggered automatically for review.

### CODE REVIEW

**Comment by kmpaul** [comment]
If you want someone's name listed as a code owner in this file, please let me know.

**Comment by jukent** [comment]
Looks good. Just to clarify this would automatically request reviews from everyone listed? 
Currently if I left a review on this PR  it "wouldn't count towards merge-ability" without my review being explicitly requested.

**Comment by brian-rose** [comment]
This looks great.

Presumably other reviewers can/will still be added manually as appropriate for each PR.

**Comment by kmpaul** [comment]
@jukent:  Yes.  The rule is, if anything is changed in the `ci/` directory, then @andersy005 and I get pinged for review.  If anything in the `content/` directory changes, then you and I get pinged for review.  If anything else changes (i.e., only in the `/` root directory), then only I get pinged for review.

@brian-rose:  Yeah.  We can always add more people later.

**Comment by dopplershift** [comment]
@kmpaul If you're going to be listed as global, it's not really serving any purpose to have you listed on the directories too. It's also not hurting anything, though.

Probably should give @jukent write-access to the repo if she's listed as in `CODEOWNERS`.

**Comment by kmpaul** [comment]
@dopplershift:  I thought that the "global" owner category was for "anything that didn't meet other criteria".  I didn't think that I would be asked for review on changes in `content/` unless I was explicitly added to that pattern.

**Comment by kmpaul** [comment]
(Also, @jukent, @dcamron, and @andersy005 should all have write access, now.)

**Comment by jukent** [comment]
> (Also, @jukent, @dcamron, and @andersy005 should all have write access, now.)

Can confirm.

**Comment by dopplershift** [comment]
@kmpaul You're right [it seems](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-code-owners) and I have learned something today. :wink:

**Review by brian-rose — APPROVED** [review]

**Review by clyne — APPROVED** [review]

**Comment by kmpaul** [comment]
Ok.  I'm going to merge.

**Pull request merged**
