### PR TITLE
Add Google Analytics block back to landing page

### LINKED ISSUE #114: page visit metrics
We need to be able to gather metrics on visits to Project Pythia. Ideally this would be done in a way that allows us to spot trends over time and the breadth of pythia content. I.e. tracking the number of visits to each page on a daily or weekly basis.

### PR DESCRIPTION
**Pull request by kmpaul**
closes #114

### CODE REVIEW

**Comment by kmpaul** [comment]
I don't know why the RTD check says it is still pending.  It is complete and you can follow the link to the docs.

**Comment by brian-rose** [comment]
I've found this several times over the past couple of weeks. Resyncing the webhook seems to cure the problem, at least for a while.

**Comment by jukent** [comment]
Kevin can you explain this a little bit? I don't see where the Google analytics are on the landing page.

**Comment by kmpaul** [comment]
@jukent:  I haven't added you to the Google Analytics account, but if you want to be added, I can add you.  You will be sent an email with information about how to log in.

**Comment by kmpaul** [comment]
@jukent:  Also, Google Analytics just tracks who visits the site.  The data is held on the Google Analytics site, not on the landing page.  

@jukent @andersy005 @dcamron I've added you all to the Google Analytics account, too.

**Review by jukent — APPROVED** [review]
Very cool. Right now our average engagement time is a single minute! Maybe we can get that up haha

**Comment by kmpaul** [comment]
Should I just merge this?  I have 1 or 2 required approvals and the website doesn't break due to this change.

**Review by brian-rose — APPROVED** [review]

**Comment by kmpaul** [comment]
Thanks, @brian-rose!

**Pull request merged**
