### PR TITLE
Add a link-checker to CI tests and nightly builds

### PR DESCRIPTION
**Pull request by brian-rose**
This PR extends our CI testing for this repo to include a link checker.

It's expected to fail currently as there are broken links in the repo (#314)

### CODE REVIEW

**Comment by brian-rose** [comment]
Need to the upstream reusable action, it should test for the existence of the `_config.yml` file before trying to modify it.

**Comment by brian-rose** [comment]
Ok, fixed that in https://github.com/ProjectPythia/cookbook-actions/pull/35.

Time to try this again.

**Comment by brian-rose** [comment]
Ok, a different approach to creating the right test environment may be needed here.

**Comment by brian-rose** [comment]
Ok, this is now gotten to the point where the failures are due to actual link failures. That's good.

**Comment by brian-rose** [comment]
Links are fixed, link checker is passing.

So merging this closes #314 

This is ready for review.

**Review by ktyle — APPROVED** [review]
Looks good!

**Pull request merged**
