### PR TITLE
Multiple Gallery Filters

### LINKED ISSUE #125: Multiple gallery filters
Currently our [Resource Gallery](https://projectpythia.org/gallery.html) uses tags under three different categories (Domains, Formats, Packages) for filtering.

How feasible is it to enable multi-dimensional filtering? e.g. Formats=Video & Packages=Xarray

I think this capability will become more important as the gallery grows.

### PR DESCRIPTION
**Pull request by jukent**
Closes #125 

Step 1 - Add a class associated with each tag to every card

### CODE REVIEW

**Comment by jukent** [comment]
I would like to add a js indicator to the filtering menu that quickly let's us see which filters are on and which are off - this cannot work yet because of the inconsistency in the filtering if the user clicks multiple tags relevant to the same card. 

Ideally I'd like the user to be able to click multiple tags from the same category and filter to both of these (numpy OR pandas) with the user having to unclick each tag to deselect it. But when tags from different categories are selected, filter to the intersection of them (numpy AND video). This requires our tagging to be separated by these categories -  a `var` dictionary associated with each card?

I know you can't get back to this till after the OOP tutorial.

**Comment by kmpaul** [comment]
@jukent:  I owe you a response, and I apologize for the delay.

> I would like to add a js indicator to the filtering menu that quickly let's us see which filters are on and which are off - this cannot work yet because of the inconsistency in the filtering if the user clicks multiple tags relevant to the same card.

:+1: Yeah.  That needs to get fixed first, for sure.

> Ideally I'd like the user to be able to click multiple tags from the same category and filter to both of these (numpy OR pandas) with the user having to unclick each tag to deselect it. But when tags from different categories are selected, filter to the intersection of them (numpy AND video). This requires our tagging to be separated by these categories - a var dictionary associated with each card?

I think that makes sense.  

Related to this is something about how to get Python data into JS.  I've been thinking about how to get the *tags* information from Python into the JS.  There isn't an easy way of doing it without going *through* the HTML itself.  That is, Python is used to write the HTML, and JS has access to the HTML.  And the two processes (Python and JS) run at different times and in different places, so there really isn't a way of just "passing a Python data structure into JS."  But there are ways of doing this.  

First, you can have Python "pass the data to HTML" and then have the JS "read the data from HTML".  That is, the Python code can write HTML that "initializes" all of the tag data.  You can do this by creating a "hidden div" with CSS classes for each selected tag (and if a tag is not in the list, assume it is unselected).  Here's how I would do that:

```html
<div id="selected-tags" class="tag1 tag2 tag3 tag4 ..." style="display: none"></div>
```

This creates a `div` element styled with `display: none` so that it is not shown on screen (even though it is in the HTML).  The `div` effectively initializes all of the tag names (`tag1`, `tag2`, ...) to the "selected" state.  Then you can write JS code that gets triggered when a tag is "selected" or "unselected":

```javascript
function toggleTag(tag) {
  var tagDiv = document.getElementById('selected-tags');
  if (tagDiv.classList.contains(tag)) {
    tagDiv.classList.remove(tag);
  } else {
    tagDiv.classList.push(tag);
  }
}
```

This approach could also be used for each category to tags (affiliations, formats, etc.).  That is, one `div` for each kind of category of tag.

Those are my thoughts.

**Comment by jukent** [comment]
Going to try Checkboxes, see this StackOverflow Q: https://stackoverflow.com/questions/48315428/how-to-make-a-filter-in-javascript-which-filters-div-by-checkboxes/48316156

**Comment by kmpaul** [comment]
That is a much better solution than mine.  The `<input type="checkbox">`{.html} HTML tags are a much better way of saving the state of each gallery card tag than the "hidden div" solution I suggested above.  :100: to this approach!

**Comment by jukent** [comment]
I'm going to remove the modal for now to focus on the javascript checkbox functionality, and then figure out how to stop the modals from opening. Because it is in the middle of a multi-line string, I can't easily comment it out. I'm making a note here of where it is (around line 154)

"""
panels_body.append(
            f"""\
---
:column: + tagged-card {tag_class_str}

<div class="d-flex gallery-card">

<div class="container">
<a href="{item["url"]}" class="text-decoration-none"><h4 class="display-4 p-0">{item["title"]}</h4></a>
<p class="card-subtitle">{authors_str}<br/>{institutions_str}</p>
<p class="my-2">{short_description}</p>
</div>
</div>
{modal_str}

+++

{tags}

"""
        )
"""

**Comment by kmpaul** [comment]
@ProjectPythia/infrastructure: This PR is failing to build, and the failure says that even though `mamba` appears to be correctly installed by the `conda-incubator/setup-miniconda` action, it cannot *find* `mamba`.  I don't know what is going on here.

This failure is happening on #151, too.

**Comment by kmpaul** [comment]
@ProjectPythia/infrastructure:  This error (`mamba` not found) is happening on the Foundations repo, too.  So, this is a more widespread problem.  I don't see any issues in the `conda-incubator/setup-miniconda` GitHub repo about this, and it seems to have only started in the last 8 hours.  If I try to install `mamba` in my own test environment, it installs and is executable.

**Comment by kmpaul** [comment]
Ok.  I believe the problem is coming from the latest release of `mamba` (0.18.0).  I fixed the version of `mamba` to 0.17.0 (last releast) and it appears to build, now.

**Comment by kmpaul** [comment]
@brian-rose @andersy005:  This is ready for review, now.

**Review by andersy005 — APPROVED** [review]

**Review by brian-rose — APPROVED** [review]
I'm reviewing *only the functionality* because I know nothing about javascript, but I love this! I played around with various checkbox combinations and didn't find any glitches. This is just what I was envisioning when I originally proposed #125. 

Great work @jukent and @kmpaul ! This is critical infrastructure.

**Pull request merged**
