### PR TITLE
Use new theme!?

### PR DESCRIPTION
**Pull request by kmpaul**
This is a first attempt to switch the Portal over to the new `sphinx-pythia-theme`.  Please let me know if this looks good or not.

### CODE REVIEW

**Comment by kmpaul** [comment]
I can already see some problems with the new theme on the Gallery:

- [ ] Hover on the filter buttons at top changes background color to the wrong color and doesn't change the text color to white
- [ ] Clicking the gallery filter buttons does not open the dropdowns.  I suspect that is because the old theme used Bootstrap 5 and this one uses the version of Bootstrap that ships with the PyData Sphinx Theme (Bootstrap 4).

**Comment by kmpaul** [comment]
I think the new portal site might be ready to go.  Please look for any problems!

**Review by dopplershift — APPROVED** [review]
Changes seem fine and at least the deployment I looked at was great!

**Review by mgrover1 — APPROVED** [review]
Looks great! Thanks @kmpaul

**Pull request merged**
