### PR TITLE
add link to event page from portal

### PR DESCRIPTION
**Pull request by jukent**
This PR adds a link to the event on the main portal page. Perhaps we want to link this differently, but this was the easiest solution I found.

Eventually we may want an "events" tab in the nav bar that lists past events, events we'll be present at or give talks/tutorials, and events that we host.

### CODE REVIEW

**Comment by jukent** [comment]
Great idea @dcamron !

**Review by mgrover1 — APPROVED** [review]

**Comment by brian-rose** [comment]
For some reason I can't see the preview for this PR. Following the preview link keeps redirecting to the home page at https://projectpythia.org.

**Comment by ktyle** [comment]
@brian-rose Yes the same for me. I had to clone this fork and build the site locally.

**Comment by jukent** [comment]
Any idea why that might be?

**Comment by ktyle** [comment]
@jukent I don't  ... we should open a separate issue about this. But in the interest of getting this merged, the only thing I would suggest is to maybe have a different background color other than white for the Cookoff button? It would make it stand out just a bit more.

**Comment by dcamron** [comment]
on the cookoff site, I went with `.secondary`, which should be the navbar Pythia Grey. I haven't previewed this, so I'm not sure how that might look

**Comment by jukent** [comment]
Screen Shot 2023-04-13 at 10 57 52 AM

I changed the button color. It stands out a bit better, but still doesn't look the best. Is it obvious that it is clickable? The curser does change when you hover over it.

**Review by ktyle — APPROVED** [review]
I think this is good enough. The fact that the text reads "Learn more here" should make it clear to most folks that this is a clickable link.

**Comment by brian-rose** [comment]
If I have a moment today, I'll try opening a bare bones PR on this repo to see if the preview is still failing.

**Comment by jukent** [comment]
Okay @brian-rose just merge when you're ready

**Comment by brian-rose** [comment]
I merged, but the changes didn't get published on the portal site.

There's something wrong with the actions that publish to GitHub Pages, which is affecting both the preview and the actual publication. The [gh-pages branch of the repo](https://github.com/ProjectPythia/projectpythia.github.io/tree/gh-pages) hasn't seen any pushes in three months.

**Pull request merged**
