### PR TITLE
Reworked links.md page

### PR DESCRIPTION
**Pull request by ktyle**
I have reworked the links document a bit:

1. Added several packages with links to tutorials, galleries, and videos if available
2. Moved a few of the items in the Introductory/Basics section to the Packages section.
3. Added several courses/multi-lesson tutorials to the Lessons and Courses section.

This is just a starting point in terms of content for these sections; just wanted to get some feedback first before proceeding.

One challenge I see is to keep this document from getting too large and unwieldy.

### CODE REVIEW

**Review by kmpaul — APPROVED** [review]
Thanks, @ktyle!  I think this looks good.  I didn't check every link, but I'm assuming they work.  (Can be fixed later, if not)

**Review by brian-rose — APPROVED** [review]
I think this looks nice and clean. As this list grows further, it may need to be subdivided more, but let's worry about that later.

**Review by andersy005 — APPROVED** [review]

**Comment by jukent** [comment]
Looks great to me -- again seems like since my review wasn't *requested* I cannot leave a review due to permissions. But it builds fine and everything looks clean. The links I tried work.

**Review by jukent — APPROVED** [review]
Looks great to me --  it builds fine, everything looks clean, and the links I tried work.

**Comment by kmpaul** [comment]
@ktyle:  Is this ready to merge?

**Comment by ktyle** [comment]
@kmpaul Ready to merge!

**Comment by kmpaul** [comment]
Thanks, @ktyle!

**Pull request merged**
