### PR TITLE
Updates to use newly updated theme

### PR DESCRIPTION
**Pull request by kmpaul**
This attempts to update the portal to use version 2021.12.7 of the Sphinx Pythia Theme.  I believe this addresses some of the issues noted in previous discussions.   Please take a look and tell me what you think!

### CODE REVIEW

**Comment by kmpaul** [comment]
@dcamron @clyne @jukent:  I'm sorry I violated our policy of starting all PRs in draft mode, but this PR is now ready to review.

**Comment by kmpaul** [comment]
Most notable changes are the unified navbar along the top and the new navigation menu in the footer.  Also note the GitHub and Twitter icons at the top-right of the page.

**Review by jukent — APPROVED** [review]

**Comment by kmpaul** [comment]
**NOTE:** I don't want to merge this PR until https://github.com/ProjectPythia/pythia-foundations#196 is finalized and ready to merge.

**Review by clyne — COMMENTED** [review]
Overall I really like the new layout. I have a few comments and nits

1. Having "Portal" on the top nav bar bothers me for some reason. It takes you to the "main" landing page for Project Pythia; the same link used for the pythia logo. I guess I don't feel the term "portal" conveys useful information in this context. There is nothing on the main page that says "Portal". Maybe "Home" or just "Project Pythia" would make more sense. I don't have a strong opinion on this and go with the consensus.

A few nits on the footer:
1. The "More about" menu items seem arbitrary. "Project Pythia" makes sense. But why "Pangeo" and "Project Jupyter"? 
2. "Submit an issue" opens a GitHub issue on https://github.com/ProjectPythia/sphinx-pythia-theme. Is this really what we want?
3. "Feedback on Project Pythia" takes you to a survey on Pythia Foundations. I like the idea of having a quick link to the Pythia Foundations survey, but I'm not sure it makes sense to have it on every footer. 
4. "Join the community" we might consider adding a link to https://projectpythia.org/index.html#join-us. I know this is in the top nav bar, but I think the redundancy is ok and that content at this link is focused on joining the community :-)

**Comment by kmpaul** [comment]
@clyne:  Yes.  I think we all need to discuss what the top navbar and the bottom menu need to contain for each site.  At the moment, I think everything there is just a placeholder until I get feedback and decisions on what they really should be.  Personally, I think we should have a common top navbar for both sites that is clear and informative.  And I think that the footer menu should have common elements for both sites *and* it should have unique content for each site.  Right now, consider everything a placeholder.

**Comment by kmpaul** [comment]
(When I created the PR, I thought it was closer to mergeable than I do now.  I wish I could make it a draft, now.)

**Comment by dcamron** [comment]
FYI at 2560x1440, Firefox 95.0.2, macos 12.1, the "single-page" background colors don't extend beyond the content column,

image

if that was intended. Current https://projectpythia.org/ extends these fully.

**Comment by kmpaul** [comment]
@dcamron:  Hmm.  I suspect that is because of some layout changes I had to make to get features from the base themes to work in this theme.  I'll look into it and see if I can find a fix.

**Comment by kmpaul** [comment]
@dcamron:  Strangely, this appears to be coming from a base theme (PyData Sphinx Theme, I think), which is where Bootstrap is imported.  I can verify that the changes made to the new theme result in the use of Bootstrap `container-xl` divisions, rather than `container-fluid` divisions.  And `container-xl` has a `max-width` of 1400px.  So, that's the problem.

I'll see if I can fix this in the theme.

**Comment by kmpaul** [comment]
Ok.  I think the latest release of the theme fixes the high-res display issues.

**Comment by clyne** [comment]
@kmpaul when I try to look at the deployment [preview](https://61de1ea438a71e654d3f4b3b--projectpythia-org.netlify.app) the link is broken....Any other way to see it?

**Comment by kmpaul** [comment]
The link works for me.

**Comment by jukent** [comment]
> Deployment Preview URL: https://61df24e328128a21c335d99a--projectpythia-org.netlify.app

I think this is the link:

Deployment Preview URL: https://61df24e328128a21c335d99a--projectpythia-org.netlify.app

It is a little confusing because at the bottom of the page it also says, "This branch has not been deployed."

**Comment by jukent** [comment]
> @kmpaul when I try to look at the deployment [preview](https://61de1ea438a71e654d3f4b3b--projectpythia-org.netlify.app) the link is broken....Any other way to see it?

@clyne I think this is the link:

Deployment Preview URL: https://61df24e328128a21c335d99a--projectpythia-org.netlify.app

It is a little confusing because at the bottom of the page it also says, "This branch has not been deployed."

**Comment by kmpaul** [comment]
@clyne:  Also, if you are getting a "Safety Warning" when you click on the link, that is just because of the way netlify works.  I've received that before, and it's just an artifact of using a special service to deploy the website.

**Comment by clyne** [comment]
> @clyne: Also, if you are getting a "Safety Warning" when you click on the link, that is just because of the way netlify works. I've received that before, and it's just an artifact of using a special service to deploy the website.
> 
> You can safely say "ignore" when you get the Safety Warning and see the site preview.

Seems to work now. No telling what I was doing wrong. Probably operator error. Thanks for the help.

**Review by clyne — APPROVED** [review]
Looks awesome! Great work.

**Review by jukent — APPROVED** [review]

**Pull request merged**
