### PR TITLE
Update meeting notes link

### LINKED ISSUE #42: Unify Meeting Notes?
Since the Pythia meetings are now public on Zoom, and we have agreed on a common meeting time, does it make sense to *join* the two working group notes documents?  We could simply alternate "who runs the meeting" (IWG or EWG chair ...or John Clyne for quarterly meetings), but we could still use the same notes document.

Thoughts?

### PR DESCRIPTION
**Pull request by kmpaul**
I have unified the two WG notes documents into 1 Google Doc, and I have updated the Pythia Google Calendar events, too.

Closes #42.

### CODE REVIEW

**Review by brian-rose — APPROVED** [review]
Looks good to me.

**Review by jukent — COMMENTED** [review]
Is it still worth noting that the meetings alternate focus?

**Review by clyne — APPROVED** [review]

**Comment by brian-rose** [comment]
> Is it still worth noting that the meetings alternate focus?

I thought the same at first, but on reflection, I think that @kmpaul may be right in removing this mention.
Goal 1 is reducing barriers to participation. We hope to get people showing up at the meeting just because they're curious and want to see what's going on, regardless of which WG happens to be meeting that week. 

Also the google calendar shows the two WGs clearly so it won't be too difficult for people to figure out.

That said, I'm totally fine either way.

**Review by ktyle — APPROVED** [review]

**Comment by kmpaul** [comment]
Cool.  Thanks!

**Pull request merged**
