### PR TITLE
Use Cookbook build and preview infrastructure

### PR DESCRIPTION
**Pull request by brian-rose**
Here's a first attempt to harmonize the GitHub actions workflows for this repo with what we're doing in our Cookbook and Foundations repos.

### CODE REVIEW

**Comment by brian-rose** [comment]
Yes, environment caching works here too, and substantially speeds up the build time.

**Comment by brian-rose** [comment]
Specific changes introduced in this PR:
- Outsourcing a lot of infrastructure code to the [Cookbook Actions](https://github.com/ProjectPythia/cookbook-actions) repo (now used by Foundations too)
- Caching of the conda/mamba environment (as we already do for other repos) to speed up build times
- Previewing on GitHub pages, removing dependence on third-party Netlify deployment for previews
- Introducing a nightly build action for continuous testing (we haven't had this for this repo before)
- Removing obsolete documentation about the Netlify deployment

This should ease our ongoing maintenance burden by aligning this repo's infrastructure with Cookbooks and Foundations.

**Comment by brian-rose** [comment]
Still to do, but in a different PR:

Add link-checking to our tests.

**Comment by brian-rose** [comment]
Also if everything in this PR is working properly, then we can/should make similar changes to the workflows in the [Cookbook Gallery](https://github.com/ProjectPythia/cookbook-gallery) repo, which is also built with sphinx.

**Review by ktyle — APPROVED** [review]

**Review by jukent — APPROVED** [review]

**Pull request merged**
