### PR TITLE
Remove old notebooks used for prototyping

### PR DESCRIPTION
**Pull request by andersy005**
This PR removes the notebooks (from git history) that were used during the early prototpye

### CODE REVIEW

**Review by brian-rose — APPROVED** [review]

**Comment by andersy005** [comment]
The RTD failure is unrelated, and it appears to be coming from the `nb_gallery_generator`

> Extension error (nb_gallery_generator):
Handler <function main at 0x7f1788883310> for event 'builder-inited' threw an exception (exception: 'title')

**Comment by brian-rose** [comment]
Sorry I guess I should have waited for the check to finish before approving...

**Comment by andersy005** [comment]
> Sorry I guess I should have waited for the check to finish before approving...

No worries... I am going to look into this `nb_gallery_generator` issue and see if it's an easy fix that can be included in this PR.

**Review by jukent — DISMISSED** [review]

**Comment by brian-rose** [comment]
I can't remember now what's the origin of `nb_gallery_generator.py`. It seems like something we may need again when we start to build out our hosted galleries. Is that not true?

**Comment by jukent** [comment]
> I can't remember now what's the origin of `nb_gallery_generator.py`. It seems like something we may need again when we start to build out our hosted galleries. Is that not true?

Yes I think it is if we want to display an example notebook gallery. We might want this in the future.

**Comment by andersy005** [comment]
> Yes I think it is if we want to display an example notebook gallery. We might want this in the future.

Restored it

**Review by brian-rose — APPROVED** [review]

**Comment by clyne** [comment]
Pending @jukent approval

**Review by jukent — APPROVED** [review]

**Pull request merged**
