### PR TITLE
Fix gallery and modals for better viewing on small screens

### LINKED ISSUE #121: Responsive Gallery: Broken display on small screens
**What happened**:

On small screens, the gallery does not look good.  You can see the problem here:

Screen Shot 2021-06-22 at 4 13 51 PM

and here:

Screen Shot 2021-06-22 at 4 17 52 PM

**What you expected to happen**:

The page should look good on all screen sizes.

**Minimal Complete Verifiable Example**:

Go to the gallery and reduce the width of your browser to as small as it will go.  Or look at it on your phone.

**Anything else we need to know?**:

I think we need some `@media` rules that change the CSS (`_static/custom.css`) depending on screen width.  Namely, on small screens I think it should display as:

- Thumbnail image above the card content, 100% width
- Modal image removed?  Might need to make the modal window scrollable?

**Environment**:

- Browser: Chrome Version 91.0.4472.114 (Official Build) (x86_64)

### PR DESCRIPTION
**Pull request by kmpaul**
I've made some CSS tweaks to the portal to improve it's look and operation on small screens.

closes #121

### CODE REVIEW

**Review by brian-rose — APPROVED** [review]
Reviewing strictly for use, as I don't "speak" CSS so the code changes don't mean much to me.

I viewed the render on a large screen and on my phone. The gallery looks great and works great on both devices.

**Comment by kmpaul** [comment]
pinging: @andersy005

**Review by andersy005 — APPROVED** [review]

**Comment by andersy005** [comment]
@kmpaul, this looks great! One idea for future work: since the resources gallery is getting long, would it be useful to have the "filter menu" as a floating menu i.e. stay in a fixed position when you scroll the page?

**Comment by kmpaul** [comment]
@andersy005:  I think a floating menu is a great idea!  Something for another PR.

**Pull request merged**
