### PR TITLE
Add Chris Cardinale to team list

### PR DESCRIPTION
**Pull request by brian-rose**

### CODE REVIEW

**Comment by brian-rose** [comment]
Closes #181

**Comment by brian-rose** [comment]
@ProjectPythia/infrastructure why does this PR not trigger any automatic review assignments?

**Comment by dopplershift** [comment]
Because the file according to CODEOWNERS was owned by "education", but that team didn't actually have write access on this repository. I've fixed that, and manually added education to review this PR.

**Review by cjcardinale — APPROVED** [review]

**Review by mgrover1 — APPROVED** [review]
Looks good to me!

**Pull request merged**
