### PR TITLE
Add link to GitHub Discussions on Portal

### PR DESCRIPTION
**Pull request by kmpaul**
This is a draft to add a link to the new GitHub Discussions page on the Portal.  Let me know what you think!

### CODE REVIEW

**Review by brian-rose — COMMENTED** [review]
Looks great! I suggest *also* adding the exact same text and links somewhere near the top of the Contributor's Guide, as this is a pathway for new contributors to get involved.

**Review by jukent — APPROVED** [review]
Links work great for me.

**Comment by jukent** [comment]
> Looks great! I suggest _also_ adding the exact same text and links somewhere near the top of the Contributor's Guide, as this is a pathway for new contributors to get involved.

I wasn't sure that I could suggest an edit to a file not previously changed by this PR so I created a [new PR](https://github.com/ProjectPythia/projectpythia.github.io/pull/25) to address this

**Review by clyne — APPROVED** [review]

**Comment by kmpaul** [comment]
@brian-rose:  Thanks for the review.  The addition to the Contributor's Guide will be handled by #25.

I'll merge now.

**Pull request merged**
