### PR TITLE
Attempt to add Google Analytics to portal

### PR DESCRIPTION
**Pull request by kmpaul**
This adds the necessary javascript to the head section of the Sphinx theme template to enable Google Analytics tracking.

### CODE REVIEW

**Comment by kmpaul** [comment]
Ok.  It doesn't look like much has changed because the HTML tags that were added to the site don't display; they just add functionality for Google Analytics to track the portal.  I think it is working, but we won't get any statistics until this gets merged.

**Review by brian-rose — APPROVED** [review]
Can't say I know anything about this, so my review is not worth much!

**Comment by andersy005** [comment]
@kmpaul, is the `template` extension approach in anticipation of the custom sphinx theme you've been developing? I am asking because google analytics could be enabled in the sphinx-book-theme via the `html_theme_options` in `conf.py`: 


```python
html_theme_options = {
    "google_analytics_id": "G-T9KGMX7VHZ",
}
```

**Comment by jukent** [comment]
It doesn't seem like this worked?

**Pull request merged**
